## Spring Properties
spring:
    ## Spring mail properties
    ## https://account.mail.ru/user/2-step-auth/passwords/
  mail:
    host: smtp.mail.ru
    username: noreply@rv-tech.online
    password: PASSWORD
    port: 465
    protocol: smtps
    properties.mail.smtp:
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
    debug: true